### ISSUE TITLE
Reparer les réglages du son et le bouton quit

### ISSUE THREAD

**Issue by EtiennePasteur** [HippoBaro/R-Type#104]
- [x] Le soundManager ne reçoit pas les événements liés au changement du volume
- [x] On ne peut pas rester appuyer sur le bouton gauche pour régler la musique
- [x] Le bouton quit ne fonctionne pas

**Comment by HippoBaro** [comment]
I'm taking this

**Comment by HippoBaro** [comment]
See #106
