### ISSUE TITLE
Creer le système de matchmaking

### ISSUE THREAD

**Issue by HippoBaro** [HippoBaro/R-Type#51]
- [x] Créer des salons d'attente
- [x] Permettre à un amis de rejoindre un salon
- [ ] Creer un système de vote pour la partition à jouer

**Comment by aguadoenzo** [comment]
Je propose le système suivant : 
 - Un joueur crée une partie -> request le serveur -> reçoit un UUID de partie.
 - Il peut donner ce UUID à d'autres joueurs pour qu'ils rejoignent sa partie
 - Ou peut signaler qu'il attend que d'autres personnes rejoignent la partie (sans le UUID, mais random du coup)

**Comment by HippoBaro** [comment]
Plutot :
1. Un joueur crée une partie -> request le serveur -> reçoit un `UUID` de partie.
2. Il peut donner ce `UUID` à d'autres joueurs pour qu'ils rejoignent sa partie.
     - D'autres joueurs se connectent en spécifiant l'`UUID` -> request serveur.
     - Le serveur informe tous les clients des évènements du `Lobby` (nouveau joueur, joueur parti...)
     - Les autres joueurs se marquent comme "*pret*" -> request serveur.
3. Quand tous les joueurs sont "*prêt*", le jeu démarre.

**Comment by EtiennePasteur** [comment]
L'utilisateur peut donner un nom a sa room/channel/partie, donc soit l'UUID équivaut a ce nom, soit on associe un UUID a un ChanelName et les autres joueurs peuvent rejoindre la partie grace a ce nom

**Comment by HippoBaro** [comment]
C'est une bonne question. Idéalement quelqu'un rejoignant une partie devrait pouvoir le faire directement par le nom de la room (évitons les uuid à rallonge).
Il est probable que, en fait, l'ID de la room reste du coté du serveur et que les clients ne connaissent des room que leurs noms.
