### ISSUE TITLE
Procédure de connection côté client

### ISSUE THREAD

**Issue by EtiennePasteur** [HippoBaro/R-Type#62]
- [x] Mettre en place les menus (SFML) coté client.
            - Create room, Join room, RoomName, Settings, etc.
- [x] Acheminer les input jusqu'au NetworkManager client.
- [x] Implémenter l'EventManager entre les différents modules.
- [ ] ~~~Implémenter le protocole "HelloWorld" pour initer la connection avec le serveur
               - GO, CREATE_ROOM, JOIN_ROOM, etc.~~~

**Comment by EtiennePasteur** [comment]
- [x] Refactoring des message de l'eventManager afin de corriger la `Dette Technique`

**Comment by Deeganx3** [comment]
#70

**Comment by EtiennePasteur** [comment]
#70
